### ISSUE TITLE
Setup a Quarkus multi-module project

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#1]
## Task

- [x] Setup a Quarkus multi-modules project
- [x] Find a better name for the github repo
- [x] Define the groupId/artifactId/version
- [x] Create the pom.xml
- [x] Rename repository
- [x] Add the needed dependencies: panache, ...

**Comment by cmoulliard** [comment]
If the task is finished, can you move it to the next column please @aureamunoz
