### ISSUE TITLE
Create the backend service watching if k8s services exist

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#17]
## TODO

- [ ] Create the backend service watching if k8s services exist against the services registered
- [ ] Add test case (mock up) able to verify/validate that the service works
- [ ] Generate the results found part of a `Services available` screen with some filter options

## Description of the service

- Create a Fabric8 Java client backend serviceable to access one of the clusters registered,
- From a list of registered services, check for each of them if there is a k8s service available within the namespaces of cluster defined local, cluster1, cluster2, ...
- The matching criteria should be to use "service name" or "alternate names" and port (e.g. mysql:3306)
- If there is a service, then create a "service available" object containing (see columns of miro screen)
- The service available should include the URL of the connection that we will pass back to a claim (= microservice requesting to bind a service). Remark: Such a URL will work for in-cluster access. What about if we discover a service running on cluster 2, 3, etc (TO BE INVESTIGATED)
- Expose a endpoint able to query the list of the "service available"
- Using `htmx` poll the endpoint every 60s by example

Questions ? @Sgitario @aureamunoz
