### ISSUE TITLE
TODO to fix workload projection

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#193]
## TODO

Tasks to be done:

- [x] Update the f8s syntax to mount only the volume and not volume + envFrom
- [x] Add the needed quarkus dependency
- [x] Find what the `Directory that stores the binding data.` should be - https://redhat-developer.github.io/service-binding-operator/userguide/projecting-binding-data/projecting-binding-data.html
- [x] Populate the secret according to the [WorkloadProjection](https://github.com/servicebinding/spec#example-secret)
- [x] Split from k8s service discovered, the host and the port as they must be passed as separate parameters to the secret
- [x] Add a method able to create properly the secret where:
       - type = DB type name in lowercase (e.g PostgreSQL -> postgresql). 
       - provider = snowdrop
       - url renamed to uri
       - host = hostname of the k8s service
       - port = port of the service
 - [x] We need a new field part of the claim to define the type AND we could reuse the Service type (to be copied to the claim field when service is selected). Remark. We should then create another field to express that Service is part of `something` which corresponds to:  SQL, NoSQL, Broker, .... Api, etc !

**Comment by cmoulliard** [comment]
Questions:

Do we need to create the `database-dir` part of the secret as this example do not include such a directory https://github.com/servicebinding/spec#example-secret ? @iocanel

**Comment by aureamunoz** [comment]
I think Ioannis responded in zulip, quoting:

_The only part where I see it differ is the use of the database, however I am not sure if the spec excludes additional fields.
On the other hand without it its impossilbe to construct the jdbc uri
And the binding framework can't possibly make assumptions on what technology the app is using and thus it's not able to assume jdbc. So, it's 100% needed._

**Comment by cmoulliard** [comment]
Here is how the Deployment should looks like (after SBO updated it) and what we should do using f8 k8s client:
```
k get deployment/spring-petclinic -n my-petclinic -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: "2022-12-02T19:03:15Z"
  generation: 2
  labels:
    app: spring-petclinic
  name: spring-petclinic
  namespace: my-petclinic
spec:
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: spring-petclinic
    spec:
      containers:
      - env:
        - name: SPRING_PROFILES_ACTIVE
          value: postgres
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        image: quay.io/service-binding/spring-petclinic:latest
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        volumeMounts:
        - mountPath: /bindings/spring-petclinic-postgresql
          name: spring-petclinic-postgresql
...
      volumes:
      - name: spring-petclinic-postgresql
        secret:
          defaultMode: 420
          secretName: spring-petclinic-postgresql-73d8585e
```

**Comment by cmoulliard** [comment]
I need your help here @iocanel @geoand 

The quarkus app that we deploy on a kind cluster running primaza fails to start as we got such an error `Model classes are defined for the default persistence unit <default> but configured datasource <default> not found: the default EntityManagerFactory will not be created. To solve this, configure the default datasource. Refer to https://quarkus.io/guides/datasource for guidance.`

Here is the project that we try to bind using Quarkus SB ext: https://github.com/aureamunoz/atomic-fruits-service

I suspect that this code https://github.com/aureamunoz/atomic-fruits-service/blob/main/src/main/resources/application.properties#L7-L14 is not correct as ENV binding should be handled by the Service Binding ext according to the workload projection (= file system mounted from the secret).

Question: How should we define the Quarkus Prod Datasource within the appliction.properties when SB Workload projection is used (= secret mounted under /bindings/name) ? 

Here is how the deployment has been populated which is similar to what SBO do (see previous comment)
```
[snowdrop@k122-centos7 primaza-poc]$ k get deployment/atomic-fruits -n app -o yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    app.quarkus.io/build-timestamp: 2022-12-05 - 11:26:18 +0000
    app.quarkus.io/commit-id: b94f5c6639c2f0714281221b0828956e595fc378
    deployment.kubernetes.io/revision: "3"
  creationTimestamp: "2022-12-05T11:26:25Z"
  generation: 5
  labels:
    app.kubernetes.io/name: atomic-fruits
    app.kubernetes.io/version: 1.0.0
  name: atomic-fruits
  namespace: app
  resourceVersion: "2902"
  uid: 2b8ad4c7-dbed-4fde-b07b-8f4ef76b68ff
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: atomic-fruits
      app.kubernetes.io/version: 1.0.0
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        app.quarkus.io/build-timestamp: 2022-12-05 - 11:26:18 +0000
        app.quarkus.io/commit-id: b94f5c6639c2f0714281221b0828956e595fc378
        kubectl.kubernetes.io/restartedAt: 2022-12-05T11:35:26.715
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: atomic-fruits
        app.kubernetes.io/version: 1.0.0
      namespace: app
    spec:
      containers:
      - env:
        - name: KUBERNETES_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: SERVICE_BINDING_ROOT
          value: /bindings
        image: localhost:5000/amunozhe/atomic-fruits:1.0.0
        imagePullPolicy: Always
        name: atomic-fruits
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /bindings/atomic-fruits-my-postgresl
          name: atomic-fruits-my-postgresl
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: atomic-fruits-my-postgresl
        secret:
          defaultMode: 420
          secretName: atomic-fruits-my-postgresl
```

**Comment by geoand** [comment]
I can't reproduce the problem

**Comment by cmoulliard** [comment]
> This error happens at build time, but when I build the supplied application with `mvn package -DskipTests`, it builds as expected

This is not a building issue but a runtime problem as quarkus cannot set the datasource using the file system mounted from the secret

**Comment by geoand** [comment]
From what I see in the source code, this error only happens at build time.

How do you reproduce this issue?

**Comment by cmoulliard** [comment]
> How do you reproduce this issue?

On a kind cluster running on hetzner VM.

**Comment by cmoulliard** [comment]
We were able to get more information using the debug mode of quarkus

```
2022-12-06 07:47:01,216 DEBUG [io.qua.kub.ser.bin.run.KubernetesServiceBindingConfigSourceProvider] (main) Found 1 potential Service Binding directories
2022-12-06 07:47:01,227 DEBUG [io.qua.kub.ser.bin.run.KubernetesServiceBindingConfigSourceProvider] (main) Directory '/bindings/atomic-fruits-my-postgresl' contains 3 properties and will be used
as Service Binding ServiceBinding{name='atomic-fruits-my-postgresl', provider='null', type='postgresql'}
2022-12-06 07:47:01,231 DEBUG [io.qua.kub.ser.bin.run.DatasourceServiceBindingConfigSourceFactory] (main) One or more of 'host' or 'database' properties were not found for datasource of type post
gresql
```

Question: So the ServiceBinding Lib of quarkus do not handle the URI BUT only the host and port. Is it correct ? AFAIK URI could also be passed - see [example](https://github.com/servicebinding/spec#example-directory-structure) but apparently this is not mandatory 

"Other than the recommended type and provider entries, there are no other reserved Secret entries. In the interests of consistency, if a Secret includes any of the following entry names, the entry value MUST meet the specified requirements". 

WDYT ? @geoand @iocanel @Sgitario

**Comment by cmoulliard** [comment]
> I guess we should also support `uri`.

It is there but declared using a different property `jdbc-url` which I suppose include the JDBC procotol ;-) - [see](https://github.com/quarkusio/quarkus/blob/9743d7e187a0e32e640e65666a097ee1a4519da6/extensions/kubernetes-service-binding/runtime/src/main/java/io/quarkus/kubernetes/service/binding/runtime/DatasourceServiceBindingConfigSourceFactory.java#L50-L54)

**Comment by geoand** [comment]
Yeah, I don't know why it was added though...

**Comment by geoand** [comment]
https://github.com/quarkusio/quarkus/pull/29702 introduces support for `uri`
