### ISSUE TITLE
Setup github actions

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#2]
## Tasks

- [x] Create a github action to build the quarkus project and publish the container image created on github.com/halkyonio repository. https://github.com/halkyonio/primaza-poc/pull/43
- [x] Setup a e2e test case able to install kind, a mysql or postgresql using helm, the quarkus application and check if the application has been claimed to access the service db: https://github.com/halkyonio/primaza-poc/pull/63
- [x] Add a mvn verify -Dnative action in the build job. https://github.com/halkyonio/primaza-poc/pull/35

Blocked by:
- Configure Quarkus Helm extension: https://github.com/halkyonio/primaza-poc/issues/55
- Configure production database: https://github.com/halkyonio/primaza-poc/issues/44

**Comment by cmoulliard** [comment]
Can you update this ticket please if done ? @jacobdotcosta

**Comment by jacobdotcosta** [comment]
I was but it got stalled with the release tasks. I'll assign it to Jose.
