### ISSUE TITLE
Improve how we claim an application (app -> claim instead of claim -> app)

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#204]
## TODO

- [x]  Switch card `claim` and `application` within the home screen: https://github.com/halkyonio/primaza-poc/pull/225
- [x]  Replace the `bind` button within the Applications list screen with `claim | claiming` button when status != new and claim do not exist for an application: https://github.com/halkyonio/primaza-poc/pull/228
- [x]  Add logic to open a `New claim` when we click on the `claim | claiming` button from application list screen: https://github.com/halkyonio/primaza-poc/pull/242
- [x]  Propose a new button when the claim succeeded (like also the status)
- [x]  Create a new field to ask the user to pass the service they would like to use (= service requested) within the claim form as currently we list the service available: https://github.com/halkyonio/primaza-poc/pull/165 and https://github.com/halkyonio/primaza-poc/pull/235
- [ ]  Provide a list of catalog services from the service requested within the Claim form
- [x]  From the submit button, add a claim and call `bindApplication` method: https://github.com/halkyonio/primaza-poc/pull/242
- [x]  Adapt the logic to add  `claim`: https://github.com/halkyonio/primaza-poc/pull/242
```
     public Response add(@Form io.halkyon.model.Claim claim, @HeaderParam("HX-Request") boolean hxRequest) {
        Set<ConstraintViolation<Claim>> errors = validator.validate(claim);
        AcceptedResponseBuilder response = AcceptedResponseBuilder.withLocation("/claim");

        if (errors.size() > 0) {
            response.withErrors(errors);
        } else {
            if (claim.created == null) {
                claim.created = new Date(System.currentTimeMillis());
            }
            if (claim.status == null) {
                claim.status = ClaimStatus.NEW.toString();
            }

            //claimingService.claimService(claim);
            claim.persist();
            // TODO: Call the bindableService method !
            response.withSuccessMessage(claim.id);
```
- [x]  Review the logic of the `bindApplication`: https://github.com/halkyonio/primaza-poc/pull/242
```
    public void bindApplication(Application application, Claim claim) {
        Credential credential = getFirstCredentialFromService(claim.service);
        // TODO Add missing logic to find the Service Available
        // TODO Add method to Calculate the URL from Service available (such logic could be called here or from screen discovered services too)
        String url = generateUrlByClaimService(application, claim);
        Claim.update("update from Claim set url = ?1, credential = ?2 where id = ?3",url,credential,claim.id);
        if (credential != null && url != null) {
            // scenario is supported
            createSecretForApplication(application, claim, credential, url);
            rolloutApplication(application);
        }
    }
```
