### ISSUE TITLE
Create the Quarkus ServiceBox application

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#3]
## Tasks

- [x] Setup the connection to use H2 in memory DB (mysql, postgresql could be also used in a future release)
- [x] Create the model classes for Claim, Service (registered, available), Credential, ....
- [x] Generate the REST endpoints able to perform CRUD operations on the different entities
- [x] Create a script to import SQL data (with some service(s), credentials(s))
- [ ] Generate the deployment using dekorate as Helm chart. Will be done as part of https://github.com/halkyonio/primaza-poc/issues/55.
- [ ] Include an ingress route to access the application from external machine. Will be done as part of https://github.com/halkyonio/primaza-poc/issues/55.

**Comment by cmoulliard** [comment]
Should we assign the last 2 tasks to Jose and move to another issue ? @cmoulliard

**Comment by aureamunoz** [comment]
I think we should create a new separated issue for the remaining tasks and close this one. wdty @cmoulliard ?

**Comment by cmoulliard** [comment]
> I think we should create a new separated issue for the remaining tasks and close this one

That was my suggestion ;-)

**Comment by Sgitario** [comment]
I've just opened https://github.com/halkyonio/primaza-poc/issues/55 to continue with the remaining tasks. Closing this one.
