### ISSUE TITLE
Filter claims search result

### ISSUE THREAD

**Issue by cmoulliard** [halkyonio/primaza-poc#82]
## TODO

- [x] Add fields needed to filter the claims using: name, service registered, ... part of the Claims list screen
- [x] Add a new endpoint supporting to build a query using parameters
- [x] Extend the test cases to validate the `filtering` queries
